name: CD Fake

on: 
  workflow_dispatch:

jobs:
  deploy-fake-dinamico:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.ref_name == 'stage' || github.ref_name == 'dev'
    environment: ${{ 
        github.ref_name == 'main' && 'producao' || 
        github.ref_name == 'stage' && 'homologacao' || 
        github.ref_name == 'dev' && 'desenvolvimento'
        }}
    env:
      AMBIENTE_DEPLOY: ${{ 
            github.ref_name == 'main' && 'producao' || 
            github.ref_name == 'stage' && 'homologacao' || 
            github.ref_name == 'dev' && 'desenvolvimento'
            }}
    steps:
      - name: Fake de deploy em ambiente
        run: echo "Deploy no ambiente de ${{ env.AMBIENTE_DEPLOY }}"
