name: CI/CD Fake
on: 
    workflow_dispatch:
      inputs:
        ambiente:
          type: choice
          required: true
          options:
            - dev
            - stage
            - prod     
          
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Build de Imagem Docker
              run: echo "Execução do comando de docker build"
            - name: Execução de Testes de Software
              run: echo "Aqui eu executo o teste de software"
            - name: Publicando a Release
              run: echo "Publicação da Relase final"
    CD-repo-local:
        needs: [CI]
        uses: isamuelalmeida/inicio-pipeline-cicd/.github/workflows/cd.yml@main
        with:
          ambiente: ${{ inputs.ambiente }}
        secrets:
          registry_user: ${{ secrets.DOCKERHUB_USERNAME }}
    CD-repo-remoto:
        needs: [CI]
        uses: isamuelalmeida/repo-deploy/.github/workflows/deploy.yml@main
        with:
          ambiente: ${{ inputs.ambiente }}
        secrets: inherit