name: Workflow Concorrência
run-name: Workflow concorrência ${{ github.run_number }}

on:
    workflow_dispatch:

concurrency: pipeline-concorrencia
# É possível executar a concorrência a nível de branch:
## concurrency:
##   group: "${{ github.ref }}-${{ github.workflow }}"
# Também é possível executar concorrência a nível de jobs

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Execução do job1
              run: |
                sleep 60
                echo "Action executada no job1"