name: Teste Container

on:
  workflow_dispatch

jobs:
  job-container:
    runs-on: ubuntu-latest
    container:
      image: python:3.10.14-alpine3.20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verificar a versão do Python
        run: python --version
      - name: Instalação do CURL no Alpine
        run: apk add curl
      - name: Executando o curl no google
        run: curl https://www.google.com
      - name: Verifica info do SO
        run: |
          pwd
          ls -la
          uname -a
          cat /etc/os-release
          ping google.com -c4
  action-container:
    runs-on: ubuntu-latest
    steps:
      - name: Observando SO do Runner
        run: |
          cat /etc/os-release
          ping google.com -c4
      - name: Observando SO do Container
        uses: docker://debian:trixie
        with:
          entrypoint: cat
          args: /etc/os-release
  # build-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #       - name: Checkout
  #         uses: actions/checkout@v4
  #       - name: Setup .NET
  #         uses: actions/setup-dotnet@v4
  #         with:
  #           dotnet-version: 8.0.x
  #       - name: Teste de Integração
  #         env:
  #           ConnectionStrings__DefaultConnection: "Host=localhost;Database=review;Username=review;Password=Passw0rd2023!"
  #         run: dotnet test ./src/Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj --verbosity normal 