name: Teste Logs

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Add mensagens de log
        run: |
          echo "::debug:: Mensagem de log debug"
          echo "::warning:: Mensagem de log warning"
          echo "::notice:: Mensagem de log notice"
          echo "::error:: Mensagem de log error"
          echo "::info:: Mensagem de log info"
        