name: Fake Self Runner

on: 
  workflow_dispatch:

env:
  DOCKER_IMAGE: saiwmon/app-node-self-runner
  DOCKER_TAG: v${{ github.run_number }}

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Fake task
        run: echo "Teste self runner..."
      - name: Obtendo o código
        uses: actions/checkout@v4.1.7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Configuração do Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build e push da imagem
        uses: docker/build-push-action@v6
        with:
          context: ./src-node
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_IMAGE }}:latest